const CONFIG = {};

// エラーメッセージ


// デフォルトデバイス
CONFIG.USER_DEVICE_DEFAULT = 'pc';

// 待機時間
CONFIG.WAIT_TIME_SHORT = 500;
CONFIG.WAIT_TIME_MIDDLE = 1500;
CONFIG.WAIT_TIME_LONG = 3000;
CONFIG.INTERVAL_TIME_CONFIRM_ORDER = 1500;
CONFIG.INTERVAL_TIME_CONFIRM_ORDER_2 = 1000;
CONFIG.INTERVAL_TIME_ORDER_CLICK = 2000;
CONFIG.INTERVAL_TIME_ORDER_CLICK_2 = 1000;
CONFIG.WAIT_TIME_ORDER_CLICK = 80;
CONFIG.WAIT_TIME_CONFIRM_CLICK = 80;

// 都道府県コード


CONFIG.LOGIN_TYPE_NUMBER = '1';
CONFIG.LOGIN_TYPE_REGISTER = '2';

module.exports = CONFIG;